name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    steps:
      # See action.yml for all options
      - name: Personal Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-left.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          
      - name: 🎼 Music plugin (playlist)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 5
